package com.example.faidingscrollview;

import android.app.ListActivity;
import android.os.Bundle;
import android.widget.ArrayAdapter;

public class MainActivity extends ListActivity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		String[] names = { "First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second", "First message second",
				"First message second" };
		setListAdapter(new ArrayAdapter<String>(this, R.layout.text_list, names));
	}
}
